
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD;

DROP TABLE TBL_BOARD;

CREATE  TABLE TBL_BOARD2(
	BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
	BOARD_TITLE VARCHAR(500) NOT NULL,
	BOARD_WRITER VARCHAR(500) NOT NULL,
	BOARD_CONTENT VARCHAR(1000) NOT NULL,
	BOARD_REGISTER_DATE DATE DEFAULT SYSDATE,
	BOARD_UPDATE_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_BOARD2
(BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
VALUES(SEQ_BOARD.NEXTVAL,'테스트 제목2', '테스트 유저2', '테스트 내용2'
);

TRUNCATE TABLE TBL_BOARD2;

SELECT * FROM TBL_BOARD2; 


SELECT * FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_BOARD';


BEGIN
  FOR i IN 101..132 LOOP
    INSERT INTO TBL_BOARD2
    (BOARD_ID, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE)
    VALUES
    (SEQ_BOARD.NEXTVAL, 
     '제목 ' || TO_CHAR(i), -- 각 레코드의 제목을 '제목 1', '제목 2'와 같이 생성
     '작성자 ' || TO_CHAR(DBMS_RANDOM.STRING('A', 10)), -- 랜덤한 10자리 문자열 생성
     '내용 ' || TO_CHAR(DBMS_RANDOM.STRING('A', 20)), -- 랜덤한 20자리 문자열 생성
     SYSDATE, -- SYSDATE로 등록일자 설정
     SYSDATE -- SYSDATE로 갱신일자 설정
    );
  END LOOP;
  COMMIT;
END;

SELECT * FROM
(
	SELECT ROWNUM R, B.* FROM
	(
	SELECT * FROM TBL_BOARD2
	ORDER BY BOARD_ID DESC
	) B
	WHERE ROWNUM <=30
)
WHERE R > 20;
